# -*- coding: utf-8 -*-
tips = ["TIP: Read Japanese newspapers. NHK News Web Easy has furigana!", 
        "TIP: Speak a little Japanese every day.", 
        "TIP: Teach your friends and family Japanese! Teachers are the best learners.",
        "TIP: If you don't already, watching Japanese TV can help with immersion!",
        "TIP: Find a Japanese pen-pal online!",
        "TIP: Try reading children's books, and then work your way up!",
        "TIP: Stroke order matters!"
        ]
        
verbs = [
 # Kuru verbs
 {'type':'kuru','english':'to come', 'kanji':u'来る', 'romaji':'kuru'},
 {'type':'kuru','english': 'to bring', 'kanji': u'持って来る', 'romaji': ('motte kuru','mottekuru')},
 # Suru verbs
 {'type':'suru','english': 'to do', 'kanji':u'する', 'romaji':'suru'},
 {'type':'suru','english': 'to get up early', 'kanji':u'早起きする', 'romaji': ('kayaokisuru','hayaoki suru')},
 {'type':'suru','english': 'to stand up', 'kanji': u'起立する', 'romaji': ('kiritsusuru','kiritsu suru')},
 {'type':'suru','english': 'to immigrate', 'kanji': u'移住する', 'romaji': ('ijyuusuru','ijyuu suru')},
 {'type':'suru','english': 'to study', 'kanji': u'勉強する', 'romaji': ('benkyousuru','benkyou suru')},
 {'type':'suru','english': 'to go to the capital', 'kanji': '上京する', 'romaji': ('jyoukyousuru','jyoukyou suru')},
 # Ru verbs
 {'type':'ru','english': 'to get up', 'kanji': u'起きる', 'romaji': 'okiru'},
 {'type':'ru','english': 'to separate', 'kanji': u'別れる', 'romaji': 'wakareru'},
 {'type':'ru','english': 'to try hard', 'kanji': u'勉める', 'romaji': 'tsutomeru'},
 {'type':'ru','english': 'to sell', 'kanji': u'売る', 'romaji': 'uru'},
 {'type':'ru','english': 'to exist', 'kanji': u'いる', 'romaji': 'iru'},
 {'type':'ru','english': 'to know', 'kanji': u'知る', 'romaji': 'shiru'},
 {'type':'ru','english': 'to make', 'kanji': u'使る', 'romaji': 'tsukaru'},
 {'type':'ru','english': 'to serve; to work under', 'kanji': u'使える', 'romaji': 'tsukaeru'},
 {'type':'ru','english': 'to enter', 'kanji': u'入る', 'romaji': 'hairu'},
 {'type':'ru','english': 'to put something in', 'kanji': u'入れる', 'romaji': 'ireru'},
 {'type':'ru','english': 'to exit', 'kanji': u'出る', 'romaji': 'deru'},
 {'type':'ru','english': 'to be born', 'kanji': u'生まれる', 'romaji': 'umareru'},
 {'type':'ru','english': 'to divide', 'kanji': u'分ける', 'romaji': 'wakeru'},
 {'type':'ru','english': 'to see', 'kanji': u'見る', 'romaji': 'miru'},
 {'type':'ru','english': 'to eat', 'kanji': u'食べる', 'romaji': 'taberu'},
 {'type':'ru','english': 'to go up', 'kanji': u'名ぼる', 'romaji': 'naboru'},
 {'type':'ru','english': 'to go out', 'kanji': u'出かける', 'romaji': 'dekakeru'},
 # Kaeru Verbs (part of u)
 {'type':'kaeru','english': 'to return', 'kanji': u'帰る', 'romaji': 'kaeru'},
 {'type':'kaeru','english': 'to bring (a person) back', 'kanji': u'連れて帰る', 'romaji': ('tsurete kaeru', 'tsuretekaeru')},
 # U Verbs
 {'type':'u','english': 'to exist (inanimate objects)', 'kanji': u'ある', 'romaji': 'aru'},
 {'type':'u','english': 'to take (a picture)', 'kanji': u'とる', 'romaji': 'toru'},
 {'type':'u','english': 'to go', 'kanji': u'行く', 'romaji': 'iku'},
 {'type':'u','english': 'to drink', 'kanji': u'飲む', 'romaji': 'nomu'},
 {'type':'u','english': 'to take something out', 'kanji': u'出す', 'romaji': 'dasu'},
 {'type':'u','english': ('to rest', 'to be absent'), 'kanji': u'休む', 'romaji': 'yasumu'},
 {'type':'u','english': 'to say', 'kanji': u'言う', 'romaji': 'iu'},
 {'type':'u','english': 'to read', 'kanji': u'読む', 'romaji': 'yomu'},
 {'type':'u','english': 'to think', 'kanji': u'思う', 'romaji': 'omou'},
 {'type':'u','english': 'to remember; to recall', 'kanji': u'思い出す', 'romaji': 'omoidasu'},
 {'type':'u','english': 'to meet', 'kanji': u'合う', 'romaji': 'au'},
 {'type':'u','english': ('to listen','to ask'), 'kanji': u'聞く', 'romaji': 'kiku'},
 {'type':'u','english': 'to buy', 'kanji': u'買う', 'romaji': 'kau'},
 {'type':'u','english': 'to stand', 'kanji': u'立つ', 'romaji': 'tatsu'},
 {'type':'u','english': 'to hold', 'kanji': u'持つ', 'romaji': 'motsu'},
 {'type':'u','english': 'to write', 'kanji': u'書く', 'romaji': 'kaku'},
 {'type':'u','english': 'to speak', 'kanji': u'話す', 'romaji': 'hanasu'},
 {'type':'u','english': 'to live', 'kanji': u'住む', 'romaji': 'sumu'},
 {'type':'u','english': 'to use', 'kanji': u'使う', 'romaji': 'tsukau'},
 {'type':'u','english': 'to work', 'kanji': u'働く', 'romaji': 'hataraku'},
 {'type':'u','english': 'to sing', 'kanji': u'歌う', 'romaji': 'utau'},
 {'type':'u','english': 'to wake someone up', 'kanji': u'起こす', 'romaji': 'okosu'},
 {'type':'u','english': 'to swim', 'kanji': u'泳ぐ', 'romaji': 'oyogu'},
 {'type':'u','english': ('to do',' to perform'), 'kanji': u'やる', 'romaji': 'yaru'},
 {'type':'u','english': ('to ride','to board'), 'kanji': u'乗る', 'romaji': 'noru'}]
 
adj = [
# Na Adjectives
{'type':'na','english': ('disgusted with','to dislike'), 'kanji':u'嫌い', 'romaji':'kirai', 'hiragana':'きらい'},
{'type':'na','english':('beautiful','clean'),'kanji':u'きれい','romaji':'kirei'},
{'type':'na','english': ('healthy','energetic'), 'kanji': u'元気', 'romaji': 'genki'},
{'type':'na','english': 'quiet', 'kanji': u'静か', 'romaji': 'shizuka'},
{'type':'na','english': 'to hate', 'kanji': u'大嫌い', 'romaji': 'daikirai'},
{'type':'na','english': ('fond of','to like'), 'kanji': u'好き', 'romaji': 'suki'},
{'type':'na','english': ('very fond of', 'to love'), 'kanji': u'大好き', 'romaji': 'daisuki'},
{'type':'na','english': 'lively', 'kanji': u'にぎやか', 'romaji': 'nigiyaka'},
{'type':'na','english': ('not busy','having free time'), 'kanji': u'暇', 'romaji': 'hima'},
{'type':'na','english': 'tough (situation)', 'kanji': u'大変', 'romaji': 'taihen'},
{'type':'na','english': 'kind', 'kanji': u'親切', 'romaji': 'shinsetsu'},
{'type':'na','english': 'convenient', 'kanji': u'便利', 'romaji': 'benri'},
{'type':'na','english': ('skillful','good at'), 'kanji': u'上手', 'romaji': 'jyouzu'},
{'type':'na','english': ('clumsy','poor at'), 'kanji': u'下手', 'romaji': 'heta'},
{'type':'na','english': 'famous', 'kanji': u'有名', 'romaji': 'yuumei'},
{'type':'na','english': 'mean spirited', 'kanji': u'意地悪', 'romaji': 'ijiwaru'},
{'type':'na','english': ('easy','simple'), 'kanji': u'簡単', 'romaji': 'kantan'},
{'type':'na','english': ('nice'), 'kanji': u'素敵', 'romaji': 'suteki'},
# II Irregular
{'type':'ii-ir','english':'good' , 'kanji': u'いい', 'romaji': 'ii'},
{'type':'ii-ir','english':'good looking', 'kanji': u'かっこいい', 'romaji': 'kakkoii'},
{'type':'ii-ir','english': ('bright','smart','clever') , 'kanji': u'頭がいい', 'romaji': ('atamagaii','atama ga ii')},
# II
{'type':'ii','english': 'early' , 'kanji': u'早い', 'romaji': 'hayai'},
{'type':'ii','english': 'new' , 'kanji': u'新しい', 'romaji': 'atarashii'},
{'type':'ii','english': 'hot (weather)', 'kanji': u'暑い', 'romaji': 'atsui'},
{'type':'ii','english': 'hot (thing)', 'kanji': u'熱い', 'romaji': 'atsui'},
{'type':'ii','english': 'busy (people/days)', 'kanji': u'忙しい', 'romaji': 'isogashii'},
{'type':'ii','english': 'large', 'kanji': u'大きい', 'romaji': 'ookii'},
{'type':'ii','english': ('interesting','funny'), 'kanji': u'面白い', 'romaji': 'omoshiroi'},
{'type':'ii','english': 'scary', 'kanji': u'怖い', 'romaji': 'kowai'},
{'type':'ii','english': 'cold (weather)', 'kanji': u'寒い', 'romaji': 'samui'},
{'type':'ii','english': 'fun', 'kanji': u'楽しい', 'romaji': 'tanoshii'},
{'type':'ii','english': 'small', 'kanji': u'小さい', 'romaji': 'chiisai'},
{'type':'ii','english': 'boring', 'kanji': u'つまらない', 'romaji': 'tsumaranai'},
{'type':'ii','english': 'old (thing)', 'kanji': u'古い', 'romaji': 'furui'},
{'type':'ii','english': 'difficult', 'kanji': u'難しい', 'romaji': 'muzukashii'},
{'type':'ii','english': ('easy (problem)','kind (person)'), 'kanji': u'やさしい', 'romaji': 'yasashii'},
{'type':'ii','english': 'inexpensive (thing)', 'kanji': u'安い', 'romaji': 'yasui'},
{'type':'ii','english': 'cute', 'kanji': u'かわいい', 'romaji': 'kawaii'},
{'type':'ii','english': 'tall (stature)', 'kanji': u'背が高い', 'romaji': ('sega takai', 'segatakai','se ga takai')},
{'type':'ii','english': 'short (stature)', 'kanji': u'背が低い', 'romaji': ('sega hikui','segahikui','se ga hikui')},
{'type':'ii','english': 'long', 'kanji': u'長い', 'romaji': 'nagai'},
{'type':'ii','english': 'fast', 'kanji': u'速い', 'romaji': 'hayai'},
{'type':'ii','english': 'short (length)', 'kanji': u'短い', 'romaji': 'mijikai'},
{'type':'ii','english': 'blue', 'kanji': u'青い', 'romaji': 'aoi'},
{'type':'ii','english': 'red', 'kanji': u'赤い', 'romaji': 'akai'},
{'type':'ii','english': 'black', 'kanji': u'黒い', 'romaji': 'kuroi'},
{'type':'ii','english': 'lonely', 'kanji': u'寂しい', 'romaji': 'sabishii'},
{'type':'ii','english': 'white', 'kanji': u'白い', 'romaji': 'shiroi'},
{'type':'ii','english': 'young', 'kanji': u'若い', 'romaji': 'wakai'},
{'type':'ii','english': 'warm', 'kanji': u'暖かい', 'romaji': 'atatakai'},
{'type':'ii','english': ('slow','late'), 'kanji': u'遅い', 'romaji': 'osoi'},
{'type':'ii','english': 'cool (weather)', 'kanji': u'涼しい', 'romaji': 'suzushii'},
{'type':'ii','english': 'cool (things/people)', 'kanji': u'冷たい', 'romaji': 'tsumetai'},
{'type':'ii','english': 'sleepy', 'kanji': u'眠い', 'romaji': 'nemui'},
{'type':'ii','english': 'sweet', 'kanji': u'甘い', 'romaji': 'amai'},
{'type':'ii','english': ('hurt','painful'), 'kanji': u'痛い', 'romaji': 'itai'},
{'type':'ii','english': 'there are many', 'kanji': u'多い', 'romaji': 'ooi'},
{'type':'ii','english': ('narrow','not spacious'), 'kanji': u'狭い', 'romaji': 'semai'},
{'type':'ii','english': ('incovenient', 'having a scheduling conflict'), 'kanji': u'都合が悪い', 'romaji': ('tsugou ga warui', 'tsugougawarui','tsugouga warui')},
{'type':'ii','english': 'bad', 'kanji': u'悪い', 'romaji': 'warui'}
]